# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170816_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='module',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
