# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170818_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
